### ISSUE TITLE
Question: When your team makes the .bin files what software do you use?

### ISSUE THREAD

**Issue by hpssjellis** [Seeed-Studio/SSCMA#136]
@LynnL4 

Question: When your team makes the .bin files what software do you use?

I assume you use the Arduino IDE and choose the export binary, but there are several other ways to compile C/C++ programs.

If you do use something other than the Arduino IDE, why? Is there a good reason to use some other IDE?

**Comment by LynnL4** [comment]
Currently the esp32 series uses the idf framework for development, and will be adapted to the Arduino platform in the future.
